// Command gentrig regenerates the committed table deliberately, never as part
// of a build. Changing it changes the simulation version and replay fixtures.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"math"
	"os"
)

func main() {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by internal/gentrig; DO NOT EDIT.\npackage fixed\n\nvar sineQuarter = [...]F{")
	for i := 0; i <= 1024; i++ {
		fmt.Fprintf(&b, "%d,", int64(math.Round(math.Sin(float64(i)*math.Pi/2048)*65536)))
		if i%12 == 11 {
			fmt.Fprintln(&b)
		}
	}
	fmt.Fprintln(&b, "\n}")
	source, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	if err = os.WriteFile("pkg/sim/fixed/sine_table.go", source, 0644); err != nil {
		panic(err)
	}
}
